---        
    apiVersion: v1
    kind: Service
    metadata:
      name: modresort-app-web-service
    spec:
      selector:
        run: modresort-app-web
      type: NodePort
      ports:
      - port: 9080
        protocol: TCP
        targetPort: 9080
